
------ REVENUE GENERATED BY COUNTRY ------
SELECT
  m.geoNetwork.country,
  SUM(IFNULL(m.totals.transactionRevenue,0)) AS revenue,
FROM 
  `bigquery-public-data.google_analytics_sample.ga_sessions_20170801` AS m
GROUP BY 
  country
ORDER BY 
  revenue DESC;
/*
Row	country	revenue
1	United States	8301950000
2	Finland	2990000
=> Only 2 countries generate revenue. It is important to think why other countries are not generating revenue. They are generating exactly 0 revenue. Even tiny markets generate a few transactions. Even low-intent countries convert a little. However, since this dataset is a curated analytics demo, the absence of revenue in other countries is almost certainly due to data limitations, not actual business performance. This suggests a data acquisition constraint.
*/